"""Constants for EasyCV backend modules.

Centralized configuration values to avoid magic numbers and improve maintainability.
"""

# File operations
BYTES_PER_KB = 1024
DEFAULT_SORT_PRIORITY = 99

# Timeouts (in seconds)
PDF_TEXT_TIMEOUT = 30
LATEX_COMPILE_TIMEOUT = 30
WORKER_DOWNLOAD_TIMEOUT = 60
DEFAULT_POLL_INTERVAL = 3

# LLM limits
DEFAULT_MAX_TOKENS_CONSOLIDATION = 4096
DEFAULT_MAX_TOKENS_RESUME = 2048
DEFAULT_MAX_TOKENS_JOB_MATCH = 4096
TEXT_TRUNCATION_LENGTH = 5000
SNIPPET_LENGTH = 40

# Log/Output limits
STDERR_LINE_LIMIT = 10
STDERR_CHAR_LIMIT = 500

# STE-100 limits
PROCEDURAL_WORD_LIMIT = 20
DESCRIPTIVE_WORD_LIMIT = 25

# Data quality thresholds
MIN_SCORE_THRESHOLD = 0.7
MAX_WARNINGS_COUNT = 10
MAX_CRITICAL_ISSUES = 3

# File size limits (in KB)
MAX_FILE_SIZE_KB = 10240  # 10MB

# Processing limits
MAX_CONCURRENT_PROCESSES = 4
MAX_RETRY_ATTEMPTS = 3
RETRY_DELAY_SECONDS = 2

# Output formatting
INDENT_SPACES = 4
MAX_LINE_LENGTH = 100