apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: convex-data-pvc
  namespace: easycv
  labels:
    app.kubernetes.io/name: convex-data
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: easycv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
